import { useState, useMemo } from "react";
import { AreaChart, Area, XAxis, YAxis, Tooltip, ResponsiveContainer, ComposedChart, Line } from "recharts";
import { useWallet } from "./hooks/useWallet";

/* ═══════════════════════════════════════════════════════════
   FISSION PROTOCOL v2 — Full Redesign
   BTC-warm palette · Custom SVG icons · Real wallet
   Flow: Landing → Markets → Strategy → Trade + Dashboard
   ═══════════════════════════════════════════════════════════ */

// ── Colors ──
const C = {
  bg: "#0A0A0F", bgCard: "#111118", bgHover: "#16161F", bgInput: "#0D0D14",
  border: "rgba(247,147,26,0.06)", borderHover: "rgba(247,147,26,0.15)",
  text: "#F0EDE8", textSec: "#9A958C", textDim: "#5A564F",
  amber: "#F7931A", amberLight: "#FFAB40",
  teal: "#2DD4A8", blue: "#5C94FF",
  red: "#EF4444", coral: "#E97880", slate: "#64748B",
  gradHero: "linear-gradient(135deg, #1a1208 0%, #0A0A0F 50%, #0d1117 100%)",
  gradBtn: "linear-gradient(135deg, #F7931A 0%, #FFAB40 100%)",
};
const font = "'Outfit', 'DM Sans', sans-serif";
const mono = "'JetBrains Mono', monospace";

// ── Chart generators ──
const mkYield = (base: number, vol: number, n = 60) => Array.from({ length: n }, (_, i) => ({
  d: i,
  underlying: +(base + Math.sin(i * 0.2) * vol + (Math.random() - 0.5) * vol * 0.6).toFixed(2),
  implied: +(base + 0.8 + Math.sin(i * 0.15) * vol * 0.5 + (Math.random() - 0.5) * vol * 0.4).toFixed(2),
  fixed: base - 0.7,
}));
const mkPT = (start: number, n = 60) => Array.from({ length: n }, (_, i) => ({
  d: i,
  price: +Math.min(start + (1 - start) * (i / n) ** 0.55 + (Math.random() - 0.5) * 0.004, 1).toFixed(4),
  target: 1.0,
}));
const mkMini = (base: number, vol: number, n = 30) => Array.from({ length: n }, (_, i) => ({
  d: i, v: +(base + Math.sin(i * 0.3) * vol + (Math.random() - 0.5) * vol * 0.5).toFixed(2),
}));
const ptMini = (start: number, n = 30) => Array.from({ length: n }, (_, i) => ({
  d: i, price: +Math.min(start + (1 - start) * (i / n) ** 0.5 + (Math.random() - 0.5) * 0.003, 1).toFixed(4),
}));

const YIELD_DATA = [mkYield(6.5, 2.2), mkYield(5.1, 3.5)];
const PT_DATA = [mkPT(0.942), mkPT(0.955)];

// ── Market config ──
interface Market {
  id: number; sym: string; name: string; protocol: string; maturity: string; daysLeft: number;
  tvl: string; vol: string; underlyingApy: number; fixedApy: number; longApy: number;
  impliedApy: number; ptPrice: number; ytPrice: number; tag: string; accent: string;
  ptSupply: string; ytSupply: string;
}
const MARKETS: Market[] = [
  { id: 0, sym: "xSTRK", name: "Endur Staked STRK", protocol: "Endur", maturity: "Jun 8, 2026", daysLeft: 92, tvl: "$2.45M", vol: "$185K", underlyingApy: 6.5, fixedApy: 5.8, longApy: 14.3, impliedApy: 7.2, ptPrice: 0.9712, ytPrice: 0.0288, tag: "STRK", accent: C.blue, ptSupply: "1200K", ytSupply: "1200K" },
  { id: 1, sym: "xLBTC", name: "Endur Staked LBTC", protocol: "Endur", maturity: "Jun 8, 2026", daysLeft: 92, tvl: "$890K", vol: "$67K", underlyingApy: 5.1, fixedApy: 4.6, longApy: 22.7, impliedApy: 8.4, ptPrice: 0.977, ytPrice: 0.023, tag: "BTC", accent: C.amber, ptSupply: "420K", ytSupply: "420K" },
];

interface Strategy {
  id: "pt" | "yt" | "split"; title: string; subtitle: string; color: string;
  risk: string; horizon: string; desc: string; details: string[];
}
const STRATEGIES: Strategy[] = [
  { id: "pt", title: "Fixed Yield", subtitle: "Buy PT", color: C.teal, risk: "Low", horizon: "Hold to maturity",
    desc: "Lock in a guaranteed fixed APY. Buy PT at a discount, redeem 1:1 at maturity. Zero exposure to rate volatility.",
    details: ["Buy PT at discount (e.g. 0.97 SY)", "Redeem 1:1 at maturity for guaranteed profit", "No risk from yield rate changes", "Best for: Conservative yield farmers"] },
  { id: "yt", title: "Long Yield", subtitle: "Buy YT", color: C.amber, risk: "High", horizon: "Active management",
    desc: "Leveraged bet on rising yield rates. Small capital, amplified returns if rates stay high or increase.",
    details: ["Buy YT for a fraction of underlying value", "Earn ALL yield generated by the position", "If rates rise → outsized returns (up to 30x)", "Best for: Yield speculators"] },
  { id: "split", title: "Split & LP", subtitle: "Mint PT + YT", color: "#8B8BFF", risk: "Medium", horizon: "Flexible",
    desc: "Deposit SY to mint equal PT + YT. Sell one side or provide LP with both for swap fees.",
    details: ["Deposit SY → receive equal PT + YT", "Provide PT+SY liquidity (0.3% fee share)", "Minimal impermanent loss at maturity", "Best for: LP providers & advanced users"] },
];

// ── SVG Icons ──
function IconShield({ size = 40, color = C.teal }: { size?: number; color?: string }) {
  return (<svg width={size} height={size} viewBox="0 0 40 40" fill="none">
    <path d="M20 4L6 10V18C6 27.1 12.04 35.52 20 38C27.96 35.52 34 27.1 34 18V10L20 4Z" stroke={color} strokeWidth="2" fill={`${color}10`} />
    <path d="M15 20L18 23L26 15" stroke={color} strokeWidth="2.5" strokeLinecap="round" strokeLinejoin="round" />
  </svg>);
}
function IconRocket({ size = 40, color = C.amber }: { size?: number; color?: string }) {
  return (<svg width={size} height={size} viewBox="0 0 40 40" fill="none">
    <path d="M20 6C20 6 14 12 14 22C14 26 16 30 20 34C24 30 26 26 26 22C26 12 20 6 20 6Z" stroke={color} strokeWidth="2" fill={`${color}10`} />
    <circle cx="20" cy="20" r="3" fill={color} />
    <path d="M14 22C10 22 8 26 8 26L14 24" stroke={color} strokeWidth="1.5" />
    <path d="M26 22C30 22 32 26 32 26L26 24" stroke={color} strokeWidth="1.5" />
  </svg>);
}
function IconAtom({ size = 40, color = "#8B8BFF" }: { size?: number; color?: string }) {
  return (<svg width={size} height={size} viewBox="0 0 40 40" fill="none">
    <ellipse cx="20" cy="20" rx="14" ry="6" stroke={color} strokeWidth="1.5" />
    <ellipse cx="20" cy="20" rx="14" ry="6" stroke={color} strokeWidth="1.5" transform="rotate(60 20 20)" />
    <ellipse cx="20" cy="20" rx="14" ry="6" stroke={color} strokeWidth="1.5" transform="rotate(120 20 20)" />
    <circle cx="20" cy="20" r="3" fill={color} />
  </svg>);
}
function IconDeposit() {
  return (<svg width="32" height="32" viewBox="0 0 32 32" fill="none"><rect x="4" y="6" width="24" height="20" rx="3" stroke={C.amber} strokeWidth="1.5" fill={`${C.amber}08`} /><path d="M16 12V22M16 22L12 18M16 22L20 18" stroke={C.amber} strokeWidth="1.5" strokeLinecap="round" /></svg>);
}
function IconSplitSvg() {
  return (<svg width="32" height="32" viewBox="0 0 32 32" fill="none"><circle cx="16" cy="8" r="4" stroke={C.amber} strokeWidth="1.5" fill={`${C.amber}08`} /><path d="M16 12V18" stroke={C.amber} strokeWidth="1.5" /><path d="M16 18L10 24" stroke={C.teal} strokeWidth="1.5" strokeLinecap="round" /><path d="M16 18L22 24" stroke={C.amber} strokeWidth="1.5" strokeLinecap="round" /><circle cx="10" cy="24" r="3" stroke={C.teal} strokeWidth="1.5" fill={`${C.teal}08`} /><circle cx="22" cy="24" r="3" stroke={C.amber} strokeWidth="1.5" fill={`${C.amber}08`} /></svg>);
}
function IconTradeSvg() {
  return (<svg width="32" height="32" viewBox="0 0 32 32" fill="none"><path d="M6 24L12 16L18 20L26 8" stroke={C.amber} strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" /><path d="M20 8H26V14" stroke={C.amber} strokeWidth="1.5" strokeLinecap="round" /><path d="M6 24L12 16L18 20L26 8V24H6Z" fill={`${C.amber}08`} /></svg>);
}
function IconRedeem() {
  return (<svg width="32" height="32" viewBox="0 0 32 32" fill="none"><circle cx="16" cy="16" r="10" stroke={C.teal} strokeWidth="1.5" fill={`${C.teal}08`} /><path d="M12 16L15 19L20 13" stroke={C.teal} strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" /></svg>);
}
function IconLP({ size = 24 }: { size?: number }) {
  return (<svg width={size} height={size} viewBox="0 0 24 24" fill="none"><path d="M12 3C7 3 3 7 3 12C3 17 7 21 12 21C17 21 21 17 21 12" stroke={C.amber} strokeWidth="1.5" strokeLinecap="round" /><path d="M21 12C21 7 17 3 12 3" stroke={C.teal} strokeWidth="1.5" strokeLinecap="round" strokeDasharray="3 3" /><circle cx="12" cy="12" r="2" fill={C.amber} /></svg>);
}
function FissionLogo({ size = 24 }: { size?: number }) {
  return (<svg width={size} height={size} viewBox="0 0 28 28" fill="none"><circle cx="14" cy="14" r="11" stroke={C.amber} strokeWidth="1.5" /><circle cx="14" cy="14" r="4" fill={C.amber} /><line x1="14" y1="3" x2="14" y2="25" stroke={C.amber} strokeWidth="0.8" opacity="0.3" /><line x1="3" y1="14" x2="25" y2="14" stroke={C.amber} strokeWidth="0.8" opacity="0.3" /></svg>);
}

function getIcon(id: string, size = 40) {
  if (id === "pt") return <IconShield size={size} color={C.teal} />;
  if (id === "yt") return <IconRocket size={size} color={C.amber} />;
  return <IconAtom size={size} color="#8B8BFF" />;
}

// ── Shared components ──
function Chip({ children, color = C.textDim }: { children: React.ReactNode; color?: string }) {
  return <span style={{ fontSize: 10, fontWeight: 600, color, padding: "3px 10px", borderRadius: 20, border: `1px solid ${color}22`, background: `${color}06`, letterSpacing: "0.02em" }}>{children}</span>;
}

function ChartTip({ active, payload }: any) {
  if (!active || !payload?.length) return null;
  return <div style={{ background: C.bgCard, border: `1px solid ${C.borderHover}`, borderRadius: 6, padding: "6px 10px", fontFamily: mono, fontSize: 11 }}>{payload.map((p: any, i: number) => <div key={i} style={{ color: p.color || C.text }}>{typeof p.value === "number" ? p.value.toFixed(2) : p.value}</div>)}</div>;
}

function TxToast({ status, hash, errorMsg, onClose }: { status: "pending" | "success" | "error"; hash: string; errorMsg?: string; onClose: () => void }) {
  const cfg = {
    pending: { color: C.amber, title: "Transaction Pending", desc: "Waiting for wallet signature..." },
    success: { color: C.teal, title: "Transaction Confirmed", desc: hash ? `${hash.slice(0, 10)}...${hash.slice(-6)}` : "Success" },
    error: { color: C.red, title: "Transaction Failed", desc: errorMsg || "Transaction was rejected" },
  }[status];
  return (
    <div style={{ position: "fixed", bottom: 20, right: 20, zIndex: 100, background: C.bgCard, border: `1px solid ${cfg.color}33`, borderRadius: 12, padding: 16, minWidth: 280, maxWidth: 400, boxShadow: `0 8px 32px rgba(0,0,0,0.5)` }}>
      <div style={{ display: "flex", justifyContent: "space-between", alignItems: "flex-start" }}>
        <div style={{ flex: 1, marginRight: 8 }}><div style={{ fontSize: 14, fontWeight: 600, color: cfg.color, marginBottom: 4 }}>{cfg.title}</div><div style={{ fontSize: 11, color: C.textSec, fontFamily: mono, wordBreak: "break-word" }}>{cfg.desc}</div></div>
        <button onClick={onClose} style={{ background: "none", border: "none", color: C.textDim, cursor: "pointer", fontSize: 16, padding: 4 }}>×</button>
      </div>
      {hash && status === "success" && <a href={`https://voyager.online/tx/${hash}`} target="_blank" rel="noreferrer" style={{ fontSize: 11, color: C.amber, marginTop: 8, display: "inline-block" }}>View on Voyager →</a>}
    </div>
  );
}

// ═══════ LANDING PAGE ═══════
function LandingPage({ onEnter }: { onEnter: () => void }) {
  return (
    <div style={{ minHeight: "100vh", background: C.bg, color: C.text, fontFamily: font }}>
      <header style={{ display: "flex", alignItems: "center", justifyContent: "space-between", padding: "0 clamp(16px,4vw,40px)", height: 64, borderBottom: `1px solid ${C.border}` }}>
        <div style={{ display: "flex", alignItems: "center", gap: 10 }}><FissionLogo /><span style={{ fontSize: 18, fontWeight: 700, letterSpacing: "-0.04em" }}>fission</span></div>
        <button onClick={onEnter} style={{ padding: "8px 20px", borderRadius: 8, border: "none", cursor: "pointer", fontSize: 13, fontWeight: 600, color: "#000", background: C.gradBtn, fontFamily: font }}>Launch App →</button>
      </header>
      <div style={{ background: C.gradHero, position: "relative" }}>
        <div style={{ position: "absolute", top: -60, left: "50%", transform: "translateX(-50%)", width: 800, height: 500, background: "radial-gradient(ellipse, rgba(247,147,26,0.06) 0%, transparent 70%)", pointerEvents: "none" }} />
        <div style={{ maxWidth: 900, margin: "0 auto", padding: "clamp(60px,10vw,100px) clamp(16px,4vw,40px) 80px", textAlign: "center", position: "relative" }}>
          <Chip color={C.amber}>RE{"{DEFINE}"} Hackathon · Bitcoin Track</Chip>
          <h1 style={{ fontSize: "clamp(32px,6vw,58px)", fontWeight: 800, letterSpacing: "-0.04em", lineHeight: 1.08, margin: "28px 0 18px" }}>Split your yield.<br /><span style={{ color: C.amber }}>Trade your future.</span></h1>
          <p style={{ fontSize: "clamp(14px,2vw,17px)", color: C.textSec, lineHeight: 1.7, maxWidth: 560, margin: "0 auto 36px", fontWeight: 300 }}>Fission tokenizes yield-bearing BTC and STRK into tradeable Principal Tokens and Yield Tokens. Lock fixed rates, speculate on yields, or earn LP fees.</p>
          <div style={{ display: "flex", gap: 12, justifyContent: "center", flexWrap: "wrap" }}>
            <button onClick={onEnter} style={{ padding: "13px 36px", borderRadius: 10, border: "none", cursor: "pointer", fontSize: 15, fontWeight: 600, color: "#000", background: C.gradBtn, fontFamily: font }}>Start Trading</button>
            <button style={{ padding: "13px 36px", borderRadius: 10, cursor: "pointer", fontSize: 15, fontWeight: 400, color: C.textSec, background: "transparent", border: `1px solid ${C.border}`, fontFamily: font }}>Read Docs</button>
          </div>
          <div style={{ display: "flex", justifyContent: "center", gap: "clamp(24px,4vw,56px)", marginTop: 72, paddingTop: 36, borderTop: `1px solid ${C.border}`, flexWrap: "wrap" }}>
            {[["$3.34M", "Total Value Locked"], ["2", "Active Markets"], ["Jun 2026", "Next Maturity"], ["Starknet", "Network"]].map(([v, l]) => (
              <div key={l} style={{ textAlign: "center" }}><div style={{ fontSize: "clamp(18px,3vw,26px)", fontWeight: 700, fontFamily: mono }}>{v}</div><div style={{ fontSize: 11, color: C.textDim, marginTop: 6, textTransform: "uppercase", letterSpacing: "0.1em", fontWeight: 500 }}>{l}</div></div>
            ))}
          </div>
        </div>
      </div>
      {/* How it works */}
      <div style={{ maxWidth: 1000, margin: "0 auto", padding: "80px clamp(16px,4vw,40px) 60px" }}>
        <div style={{ textAlign: "center", marginBottom: 52 }}>
          <div style={{ fontSize: 11, color: C.amber, textTransform: "uppercase", letterSpacing: "0.12em", fontWeight: 600, marginBottom: 10 }}>How it works</div>
          <h2 style={{ fontSize: "clamp(22px,4vw,32px)", fontWeight: 700, letterSpacing: "-0.03em" }}>Four steps to yield mastery</h2>
        </div>
        <div style={{ display: "grid", gridTemplateColumns: "repeat(auto-fit, minmax(200px, 1fr))", gap: 2 }}>
          {[{ icon: <IconDeposit />, title: "Deposit", desc: "Deposit yield-bearing tokens (xSTRK or xLBTC) into the SY wrapper", num: "01" },
            { icon: <IconSplitSvg />, title: "Split", desc: "Split SY into Principal Token (PT) and Yield Token (YT)", num: "02" },
            { icon: <IconTradeSvg />, title: "Trade", desc: "Buy PT for fixed yield or YT for leveraged exposure", num: "03" },
            { icon: <IconRedeem />, title: "Redeem", desc: "Redeem PT 1:1 at maturity, claim yield from YT anytime", num: "04" },
          ].map(s => (
            <div key={s.num} style={{ background: C.bgCard, padding: 28, borderTop: `2px solid ${s.num === "01" ? C.amber + "33" : C.border}` }}>
              <div style={{ fontSize: 10, fontWeight: 700, color: C.amber, fontFamily: mono, marginBottom: 16, opacity: 0.6 }}>{s.num}</div>
              <div style={{ marginBottom: 12 }}>{s.icon}</div><div style={{ fontSize: 16, fontWeight: 600, marginBottom: 8 }}>{s.title}</div>
              <div style={{ fontSize: 13, color: C.textSec, lineHeight: 1.6, fontWeight: 300 }}>{s.desc}</div>
            </div>
          ))}
        </div>
      </div>
      {/* Strategies */}
      <div style={{ maxWidth: 1000, margin: "0 auto", padding: "40px clamp(16px,4vw,40px) 100px" }}>
        <div style={{ textAlign: "center", marginBottom: 52 }}>
          <div style={{ fontSize: 11, color: C.amber, textTransform: "uppercase", letterSpacing: "0.12em", fontWeight: 600, marginBottom: 10 }}>Strategies</div>
          <h2 style={{ fontSize: "clamp(22px,4vw,32px)", fontWeight: 700, letterSpacing: "-0.03em" }}>Choose your yield profile</h2>
        </div>
        <div style={{ display: "grid", gridTemplateColumns: "repeat(auto-fit, minmax(280px, 1fr))", gap: 16 }}>
          {STRATEGIES.map(s => (
            <div key={s.id} style={{ background: C.bgCard, borderRadius: 16, border: `1px solid ${C.border}`, overflow: "hidden", transition: "all 0.3s", cursor: "pointer" }}
              onMouseEnter={e => { (e.currentTarget as HTMLElement).style.borderColor = `${s.color}33`; (e.currentTarget as HTMLElement).style.transform = "translateY(-4px)"; }}
              onMouseLeave={e => { (e.currentTarget as HTMLElement).style.borderColor = C.border; (e.currentTarget as HTMLElement).style.transform = "translateY(0)"; }}
              onClick={onEnter}>
              <div style={{ height: 2, background: `linear-gradient(90deg, ${s.color}, transparent)` }} />
              <div style={{ padding: "28px 24px 24px" }}>
                {getIcon(s.id, 44)}
                <div style={{ fontSize: 20, fontWeight: 700, marginTop: 16, marginBottom: 4 }}>{s.title}</div>
                <div style={{ fontSize: 12, color: s.color, fontWeight: 600, marginBottom: 14 }}>{s.subtitle}</div>
                <div style={{ fontSize: 13, color: C.textSec, lineHeight: 1.65, marginBottom: 18, fontWeight: 300 }}>{s.desc}</div>
                <div style={{ display: "flex", gap: 8 }}><Chip color={s.color}>Risk: {s.risk}</Chip><Chip>{s.horizon}</Chip></div>
              </div>
            </div>
          ))}
        </div>
      </div>
      <footer style={{ borderTop: `1px solid ${C.border}`, padding: "24px clamp(16px,4vw,40px)", display: "flex", justifyContent: "space-between", alignItems: "center", fontSize: 11, color: C.textDim, flexWrap: "wrap", gap: 8 }}>
        <div style={{ display: "flex", alignItems: "center", gap: 8 }}><FissionLogo size={16} /><span style={{ fontWeight: 600, color: C.textSec }}>fission protocol</span></div>
        <div style={{ display: "flex", gap: 20 }}>{["Docs", "GitHub", "Twitter"].map(l => <span key={l} style={{ cursor: "pointer" }}>{l}</span>)}</div>
        <span>Starknet Mainnet</span>
      </footer>
    </div>
  );
}

// ═══════ MARKETS PAGE ═══════
function MarketsPage({ onSelect }: { onSelect: (id: number) => void }) {
  return (
    <div style={{ maxWidth: 900, margin: "0 auto", padding: "48px 20px" }}>
      <h2 style={{ fontSize: 26, fontWeight: 700, letterSpacing: "-0.03em", marginBottom: 6 }}>Markets</h2>
      <p style={{ fontSize: 13, color: C.textSec, fontWeight: 300, marginBottom: 32 }}>Select a yield-bearing market to trade</p>
      <div style={{ display: "grid", gridTemplateColumns: "repeat(auto-fit, minmax(340px, 1fr))", gap: 16 }}>
        {MARKETS.map(m => (
          <button key={m.id} onClick={() => onSelect(m.id)} style={{ background: C.bgCard, borderRadius: 14, border: `1px solid ${C.border}`, padding: 24, cursor: m.id === 1 ? "default" : "pointer", textAlign: "left", transition: "all 0.25s", fontFamily: font, color: C.text, width: "100%", position: "relative", opacity: m.id === 1 ? 0.6 : 1 }}
            onMouseEnter={e => { if (m.id === 0) { (e.currentTarget as HTMLElement).style.borderColor = `${m.accent}33`; (e.currentTarget as HTMLElement).style.transform = "translateY(-3px)"; } }}
            onMouseLeave={e => { (e.currentTarget as HTMLElement).style.borderColor = C.border; (e.currentTarget as HTMLElement).style.transform = "translateY(0)"; }}>
            {m.id === 1 && <div style={{ position: "absolute", top: 12, right: 12, fontSize: 10, fontWeight: 600, color: C.amber, padding: "3px 10px", borderRadius: 20, border: `1px solid ${C.amber}33`, background: `${C.amber}10` }}>Coming Soon</div>}
            <div style={{ display: "flex", justifyContent: "space-between", alignItems: "center", marginBottom: 18 }}>
              <div style={{ display: "flex", alignItems: "center", gap: 12 }}>
                <div style={{ width: 40, height: 40, borderRadius: 12, background: `${m.accent}10`, display: "flex", alignItems: "center", justifyContent: "center", fontWeight: 700, fontSize: 15, color: m.accent }}>{m.sym[0]}</div>
                <div><div style={{ fontSize: 17, fontWeight: 700 }}>{m.sym}</div><div style={{ fontSize: 11, color: C.textDim, fontWeight: 300 }}>{m.protocol} · {m.name}</div></div>
              </div>
              <Chip color={m.accent}>{m.tag}</Chip>
            </div>
            <div style={{ display: "grid", gridTemplateColumns: "repeat(4, 1fr)", gap: 12 }}>
              {([["Fixed APY", `${m.fixedApy}%`, C.teal], ["Long Yield", `${m.longApy}%`, C.amber], ["TVL", m.tvl, C.text], ["Maturity", `${m.daysLeft}d`, C.coral]] as const).map(([l, v, c]) => (
                <div key={l}><div style={{ fontSize: 9, color: C.textDim, textTransform: "uppercase", letterSpacing: "0.1em", marginBottom: 5, fontWeight: 500 }}>{l}</div><div style={{ fontSize: 15, fontWeight: 600, fontFamily: mono, color: c }}>{v}</div></div>
              ))}
            </div>
          </button>
        ))}
      </div>
    </div>
  );
}

// ═══════ STRATEGY SELECTION ═══════
function StrategyPage({ market, onSelect, onBack }: { market: number; onSelect: (s: string) => void; onBack: () => void }) {
  const m = MARKETS[market];
  const charts: Record<string, { d: number; v?: number; price?: number }[]> = { pt: ptMini(0.94), yt: mkMini(m.longApy, 6), split: mkMini(m.underlyingApy, 2) };
  return (
    <div style={{ maxWidth: 1020, margin: "0 auto", padding: "32px 20px" }}>
      <button onClick={onBack} style={{ background: "none", border: "none", color: C.textSec, cursor: "pointer", fontSize: 13, fontFamily: font, marginBottom: 24, fontWeight: 400 }}>← Back to Markets</button>
      <div style={{ display: "flex", alignItems: "center", gap: 12, marginBottom: 6 }}>
        <div style={{ width: 36, height: 36, borderRadius: 10, background: `${m.accent}10`, display: "flex", alignItems: "center", justifyContent: "center", fontWeight: 700, fontSize: 14, color: m.accent }}>{m.sym[0]}</div>
        <h2 style={{ fontSize: 24, fontWeight: 700, letterSpacing: "-0.03em" }}>{m.sym} Market</h2>
        <Chip color={m.accent}>{m.tag}</Chip>
      </div>
      <p style={{ fontSize: 13, color: C.textSec, marginBottom: 36, fontWeight: 300 }}>Underlying APY: <span style={{ color: C.blue, fontFamily: mono, fontWeight: 600 }}>{m.underlyingApy}%</span> · Maturity: <span style={{ color: C.coral, fontFamily: mono }}>{m.maturity}</span> · TVL: <span style={{ fontFamily: mono }}>{m.tvl}</span></p>
      <div style={{ fontSize: 11, color: C.amber, textTransform: "uppercase", letterSpacing: "0.12em", fontWeight: 600, marginBottom: 20 }}>Choose Your Strategy</div>
      <div style={{ display: "grid", gridTemplateColumns: "repeat(auto-fit, minmax(280px, 1fr))", gap: 16 }}>
        {STRATEGIES.map(s => {
          const apyVal = s.id === "pt" ? m.fixedApy : s.id === "yt" ? m.longApy : m.underlyingApy;
          return (
            <div key={s.id} onClick={() => onSelect(s.id)} style={{ background: C.bgCard, borderRadius: 16, border: `1px solid ${C.border}`, cursor: "pointer", transition: "all 0.3s", overflow: "hidden" }}
              onMouseEnter={e => { (e.currentTarget as HTMLElement).style.borderColor = `${s.color}44`; (e.currentTarget as HTMLElement).style.transform = "translateY(-4px)"; }}
              onMouseLeave={e => { (e.currentTarget as HTMLElement).style.borderColor = C.border; (e.currentTarget as HTMLElement).style.transform = "translateY(0)"; }}>
              <div style={{ height: 2, background: `linear-gradient(90deg, ${s.color}, transparent)` }} />
              <div style={{ padding: "22px 20px 14px" }}>
                <div style={{ display: "flex", justifyContent: "space-between", alignItems: "flex-start" }}>
                  {getIcon(s.id, 40)}
                  <div style={{ textAlign: "right" }}><div style={{ fontSize: 9, color: C.textDim, textTransform: "uppercase", letterSpacing: "0.1em", fontWeight: 500 }}>APY</div><div style={{ fontSize: 24, fontWeight: 700, fontFamily: mono, color: s.color }}>{apyVal}%</div></div>
                </div>
                <div style={{ fontSize: 19, fontWeight: 700, marginTop: 12, marginBottom: 2 }}>{s.title}</div>
                <div style={{ fontSize: 12, color: s.color, fontWeight: 600, marginBottom: 10 }}>{s.subtitle}</div>
              </div>
              <div style={{ padding: "0 6px", height: 72 }}>
                <ResponsiveContainer width="100%" height={72}>
                  <AreaChart data={charts[s.id]}><defs><linearGradient id={`gs-${s.id}`} x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stopColor={s.color} stopOpacity={0.15} /><stop offset="100%" stopColor={s.color} stopOpacity={0} /></linearGradient></defs>
                    <Area dataKey={s.id === "pt" ? "price" : "v"} stroke={s.color} fill={`url(#gs-${s.id})`} strokeWidth={1.5} dot={false} /></AreaChart>
                </ResponsiveContainer>
              </div>
              <div style={{ padding: "10px 20px 18px" }}>
                <div style={{ fontSize: 12, color: C.textSec, lineHeight: 1.55, marginBottom: 14, fontWeight: 300 }}>{s.desc}</div>
                <div style={{ display: "flex", gap: 6, marginBottom: 14 }}><Chip color={s.color}>Risk: {s.risk}</Chip><Chip>{s.horizon}</Chip></div>
                <div style={{ padding: "11px 0", borderRadius: 10, background: s.color, color: s.id === "yt" ? "#000" : "#fff", fontSize: 13, fontWeight: 600, textAlign: "center", fontFamily: font }}>
                  {s.id === "pt" ? "Lock Fixed Yield →" : s.id === "yt" ? "Long Yield →" : "Split & LP →"}
                </div>
              </div>
            </div>
          );
        })}
      </div>
      <div style={{ marginTop: 20, background: C.bgCard, border: `1px solid ${C.border}`, borderRadius: 12, padding: "16px 22px", display: "flex", alignItems: "center", gap: 14, flexWrap: "wrap" }}>
        <IconLP size={28} />
        <div style={{ flex: 1, minWidth: 200 }}><div style={{ fontSize: 13, fontWeight: 600, marginBottom: 2 }}>Liquidity providers earn <span style={{ color: C.amber }}>0.3%</span> on every swap</div><div style={{ fontSize: 11, color: C.textSec, fontWeight: 300 }}>All strategies route through the Fission AMM. LP is integrated into the Split strategy.</div></div>
        <Chip color={C.amber}>~4.2% APY</Chip>
      </div>
    </div>
  );
}

// ═══════ TRADE PAGE ═══════
function TradePage({ market, strategy, onBack, w }: { market: number; strategy: string; onBack: () => void; w: ReturnType<typeof useWallet> }) {
  const m = MARKETS[market];
  const s = STRATEGIES.find(x => x.id === strategy)!;
  const [amt, setAmt] = useState("");
  const [txStatus, setTxStatus] = useState<"pending" | "success" | "error" | null>(null);
  const [txError, setTxError] = useState("");
  const apyVal = strategy === "pt" ? m.fixedApy : strategy === "yt" ? m.longApy : m.underlyingApy;
  const rcv = `PT + YT`;
  const out = useMemo(() => { const a = parseFloat(amt); if (!a) return "0.0000"; return a.toFixed(4); }, [amt]);
  const chartData: any[] = strategy === "pt" ? PT_DATA[market] : YIELD_DATA[market];

  const doTx = async () => {
    if (!amt || parseFloat(amt) <= 0) return;
    if (market === 1) { setTxError("xLBTC market coming soon"); setTxStatus("error"); return; }
    setTxStatus("pending");
    setTxError("");
    try {
      // All strategies: xSTRK → approve → SY deposit → approve SY → split PT+YT
      // Single atomic multicall (4 contract calls in 1 tx)
      const txHash = await w.depositAndSplit(amt);
      if (txHash) { setTxStatus("success"); setAmt(""); }
      else setTxStatus("error");
    } catch (e: any) {
      console.error("Transaction error:", e);
      const msg = e?.message || String(e);
      if (msg.includes("Execute failed")) {
        setTxError("Transaction failed. Check your xSTRK balance and try a smaller amount.");
      } else if (msg.includes("rejected") || msg.includes("abort") || msg.includes("cancel")) {
        setTxError("Transaction was rejected in wallet.");
      } else if (msg.includes("low bal") || msg.includes("insufficient")) {
        setTxError("Insufficient xSTRK balance.");
      } else {
        setTxError(msg.length > 150 ? msg.slice(0, 150) + "..." : msg);
      }
      setTxStatus("error");
    }
  };

  return (
    <div style={{ maxWidth: 1100, margin: "0 auto", padding: "32px 20px" }}>
      <button onClick={onBack} style={{ background: "none", border: "none", color: C.textSec, cursor: "pointer", fontSize: 13, fontFamily: font, marginBottom: 24, fontWeight: 400 }}>← Back to strategies</button>
      <div style={{ display: "flex", gap: 20, flexWrap: "wrap" }}>
        {/* LEFT */}
        <div style={{ flex: "1 1 500px", minWidth: 0, display: "flex", flexDirection: "column", gap: 16 }}>
          <div style={{ background: C.bgCard, borderRadius: 14, border: `1px solid ${C.border}`, padding: 22 }}>
            <div style={{ display: "flex", alignItems: "center", gap: 14 }}>
              {getIcon(s.id, 36)}
              <div style={{ flex: 1 }}><div style={{ fontSize: 18, fontWeight: 700 }}>{s.title} · {m.sym}</div><div style={{ fontSize: 12, color: C.textSec, fontWeight: 300 }}>{s.subtitle} · {m.protocol}</div></div>
              <div style={{ textAlign: "right" }}><div style={{ fontSize: 9, color: C.textDim, textTransform: "uppercase", letterSpacing: "0.1em", fontWeight: 500 }}>APY</div><div style={{ fontSize: 26, fontWeight: 700, fontFamily: mono, color: s.color }}>{apyVal}%</div></div>
            </div>
            <div style={{ fontSize: 12, color: C.textSec, lineHeight: 1.6, padding: "12px 14px", background: C.bgInput, borderRadius: 10, marginTop: 14, fontWeight: 300 }}>{s.desc}</div>
          </div>
          <div style={{ background: C.bgCard, borderRadius: 14, border: `1px solid ${C.border}`, padding: "18px 18px 10px" }}>
            <div style={{ fontSize: 13, fontWeight: 600, marginBottom: 14 }}>{strategy === "pt" ? "PT Price → 1.0 at Maturity" : "Yield Rate History"}<span style={{ fontSize: 11, color: C.textDim, marginLeft: 8, fontWeight: 300 }}>60d</span></div>
            <ResponsiveContainer width="100%" height={200}>
              {strategy === "pt" ? (
                <ComposedChart data={chartData}>
                  <defs><linearGradient id="gTr" x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stopColor={s.color} stopOpacity={0.12} /><stop offset="100%" stopColor={s.color} stopOpacity={0} /></linearGradient></defs>
                  <XAxis dataKey="d" tick={false} axisLine={false} tickLine={false} /><YAxis tick={{ fill: C.textDim, fontSize: 10 }} axisLine={false} tickLine={false} width={36} domain={[0.93, 1.01]} />
                  <Tooltip content={<ChartTip />} /><Line dataKey="target" stroke={C.textDim} strokeWidth={1} strokeDasharray="4 3" dot={false} /><Area dataKey="price" stroke={s.color} fill="url(#gTr)" strokeWidth={1.5} dot={false} />
                </ComposedChart>
              ) : (
                <ComposedChart data={chartData}>
                  <defs><linearGradient id="gTu" x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stopColor={C.blue} stopOpacity={0.12} /><stop offset="100%" stopColor={C.blue} stopOpacity={0} /></linearGradient></defs>
                  <XAxis dataKey="d" tick={false} axisLine={false} tickLine={false} /><YAxis tick={{ fill: C.textDim, fontSize: 10 }} axisLine={false} tickLine={false} width={28} unit="%" />
                  <Tooltip content={<ChartTip />} /><Area dataKey="underlying" name="Underlying" stroke={C.blue} fill="url(#gTu)" strokeWidth={1.5} dot={false} /><Area dataKey="implied" name="Implied" stroke={C.amber} fill="none" strokeWidth={1.5} dot={false} /><Line dataKey="fixed" name="Fixed" stroke={C.teal} strokeWidth={1} strokeDasharray="4 3" dot={false} />
                </ComposedChart>
              )}
            </ResponsiveContainer>
          </div>
          <div style={{ background: C.bgCard, borderRadius: 14, border: `1px solid ${C.border}`, padding: 22 }}>
            <div style={{ fontSize: 12, fontWeight: 600, color: C.textSec, marginBottom: 14 }}>Market Details</div>
            <div style={{ display: "grid", gridTemplateColumns: "repeat(3, 1fr)", gap: "14px 24px" }}>
              {([["Underlying APY", `${m.underlyingApy}%`, C.blue], ["Implied APY", `${m.impliedApy}%`, C.amber], ["PT Price", `${m.ptPrice} SY`, C.text],
                ["Maturity", `${m.daysLeft}d left`, C.coral], ["24h Volume", m.vol, C.text], ["Protocol", m.protocol, C.textSec],
                ["PT Supply", m.ptSupply, C.textSec], ["YT Supply", m.ytSupply, C.textSec], ["YT Price", `${m.ytPrice} SY`, C.text]] as [string, string, string][]).map(([l, v, c], i) => (
                <div key={i}><div style={{ fontSize: 9, color: C.textDim, textTransform: "uppercase", letterSpacing: "0.1em", marginBottom: 4, fontWeight: 500 }}>{l}</div><div style={{ fontSize: 13, fontWeight: 500, fontFamily: mono, color: c }}>{v}</div></div>
              ))}
            </div>
          </div>
          {w.connected && (
            <div style={{ background: C.bgCard, borderRadius: 14, border: `1px solid ${C.border}`, padding: 22 }}>
              <div style={{ fontSize: 12, fontWeight: 600, color: C.textSec, marginBottom: 14 }}>Your Positions</div>
              {[{ token: "PT-xSTRK", amount: w.balances.PT, apy: "5.8%", color: C.teal }, { token: "YT-xSTRK", amount: w.balances.YT, apy: "14.3%", color: C.amber }, { token: "SY-xSTRK", amount: w.balances.SY, apy: "-", color: C.blue }]
                .filter(p => p.amount !== "0" && parseFloat(p.amount) > 0).map((p, i) => (
                  <div key={i} style={{ display: "flex", justifyContent: "space-between", padding: "10px 0", borderBottom: `1px solid ${C.border}` }}><div><div style={{ fontSize: 13, fontWeight: 500 }}>{p.token}</div><div style={{ fontSize: 11, color: C.textDim, fontFamily: mono }}>{p.amount}</div></div><div style={{ fontSize: 12, fontFamily: mono, color: p.color, fontWeight: 600, alignSelf: "center" }}>{p.apy}</div></div>
                ))}
              {parseFloat(w.balances.PT || "0") === 0 && parseFloat(w.balances.YT || "0") === 0 && parseFloat(w.balances.SY || "0") === 0 && <div style={{ fontSize: 12, color: C.textDim, textAlign: "center", padding: 16 }}>No positions yet</div>}
            </div>
          )}
        </div>
        {/* RIGHT: Trade panel */}
        <div style={{ flex: "0 0 370px", minWidth: 320 }}>
          <div style={{ background: C.bgCard, borderRadius: 14, border: `1px solid ${C.border}`, position: "sticky", top: 80 }}>
            <div style={{ padding: "16px 22px", borderBottom: `1px solid ${C.border}`, display: "flex", alignItems: "center", gap: 10 }}>
              {getIcon(s.id, 20)}<span style={{ fontSize: 14, fontWeight: 600 }}>{s.title}</span><span style={{ fontSize: 12, color: s.color, fontWeight: 600, fontFamily: mono, marginLeft: "auto" }}>{apyVal}% APY</span>
            </div>
            <div style={{ padding: 22 }}>
              <div style={{ background: C.bgInput, borderRadius: 10, padding: "12px 14px", border: `1px solid ${C.border}`, marginBottom: 8 }}>
                <div style={{ display: "flex", justifyContent: "space-between", marginBottom: 8, fontSize: 10, color: C.textDim, textTransform: "uppercase", letterSpacing: "0.06em", fontWeight: 500 }}>
                  <span>You pay</span>
                  <span style={{ cursor: "pointer" }} onClick={() => setAmt(w.connected ? w.balances.xSTRK : "0")}>Bal: <span style={{ color: C.textSec, fontFamily: mono }}>{w.connected ? w.balances.xSTRK : "0"}</span> <span style={{ color: C.amber, fontWeight: 600 }}>MAX</span></span>
                </div>
                <div style={{ display: "flex", alignItems: "center", gap: 8 }}>
                  <input value={amt} onChange={e => setAmt(e.target.value)} placeholder="0.00" type="number" style={{ flex: 1, background: "transparent", border: "none", outline: "none", color: C.text, fontSize: 22, fontWeight: 500, fontFamily: mono }} />
                  <div style={{ padding: "6px 12px", background: C.bg, borderRadius: 8, fontSize: 12, fontWeight: 600, color: C.textSec, border: `1px solid ${C.border}` }}>xSTRK</div>
                </div>
              </div>
              <div style={{ display: "flex", justifyContent: "center", padding: "4px 0" }}><div style={{ width: 30, height: 30, borderRadius: 8, background: C.bgInput, border: `1px solid ${C.border}`, display: "flex", alignItems: "center", justifyContent: "center", fontSize: 14, color: C.textDim }}>↓</div></div>
              <div style={{ background: C.bgInput, borderRadius: 10, padding: "12px 14px", border: `1px solid ${C.border}`, marginBottom: 18 }}>
                <div style={{ fontSize: 10, color: C.textDim, textTransform: "uppercase", letterSpacing: "0.06em", marginBottom: 8, fontWeight: 500 }}>You receive</div>
                <div style={{ display: "flex", alignItems: "center", gap: 8 }}>
                  <span style={{ fontFamily: mono, fontSize: 22, fontWeight: 500, color: s.color }}>{out}</span>
                  <div style={{ marginLeft: "auto", padding: "6px 12px", background: C.bg, borderRadius: 8, fontSize: 12, fontWeight: 600, color: s.color, border: `1px solid ${s.color}22` }}>{rcv}</div>
                </div>
              </div>
              <div style={{ fontSize: 12, marginBottom: 18 }}>
                {([["APY", `${apyVal}%`, s.color], ["Price Impact", "<0.01%", C.teal], ["Route", "xSTRK → SY → Split → PT + YT", C.textSec], ["Fee", "0.30%", C.textSec]] as [string, string, string][]).map(([l, v, c], i) => (
                  <div key={i} style={{ display: "flex", justifyContent: "space-between", padding: "7px 0", borderBottom: i < 3 ? `1px solid ${C.border}` : "none" }}>
                    <span style={{ color: C.textDim, fontWeight: 300 }}>{l}</span><span style={{ fontFamily: mono, fontWeight: 500, color: c, fontSize: 11 }}>{v}</span>
                  </div>
                ))}
              </div>
              <button onClick={() => w.connected ? doTx() : w.connect()} style={{ width: "100%", padding: "13px 0", borderRadius: 10, border: "none", cursor: "pointer", fontSize: 14, fontWeight: 600, fontFamily: font, color: !w.connected ? "#000" : (s.id === "yt" ? "#000" : "#fff"), background: !w.connected ? C.gradBtn : (market === 1 ? C.textDim : s.color), opacity: market === 1 ? 0.5 : 1 }}>
                {!w.connected ? "Connect Wallet" : market === 1 ? "xLBTC Coming Soon" : strategy === "pt" ? "Lock Fixed Yield" : strategy === "yt" ? "Long Yield" : "Split → PT + YT"}
              </button>
              {w.connected && market === 0 && (
                <div style={{ marginTop: 10, padding: "9px 12px", background: `${C.teal}06`, borderRadius: 8, border: `1px solid ${C.teal}12`, fontSize: 10, color: C.textSec, lineHeight: 1.5, fontWeight: 300 }}>
                  {strategy === "pt" ? "Deposits xSTRK → wraps to SY → splits into PT + YT. You receive PT (fixed yield) + YT (variable yield)."
                    : strategy === "yt" ? "Deposits xSTRK → wraps to SY → splits into PT + YT. You receive YT (leveraged yield exposure) + PT (sell for instant profit)."
                    : "Deposits xSTRK → wraps to SY → splits into PT + YT. You receive both tokens to provide LP or trade."}
                </div>
              )}
              {strategy === "split" && (
                <div style={{ marginTop: 10, padding: "11px 14px", background: `${C.amber}06`, borderRadius: 10, border: `1px solid ${C.amber}15`, fontSize: 11, color: C.textSec, lineHeight: 1.55, fontWeight: 300 }}>
                  <div style={{ display: "flex", alignItems: "center", gap: 6, marginBottom: 4 }}><IconLP size={16} /><strong style={{ color: C.amber, fontWeight: 600 }}>Add LP after split</strong></div>
                  Provide PT + SY liquidity to earn swap fees (~4.2% APY).
                </div>
              )}
              </div>
          </div>
        </div>
      </div>
      {txStatus && <TxToast status={txStatus} hash={w.lastTxHash} errorMsg={txError} onClose={() => { setTxStatus(null); setTxError(""); }} />}
    </div>
  );
}

// ═══════ DASHBOARD ═══════
function DashboardPage({ w }: { w: ReturnType<typeof useWallet> }) {
  return (
    <div style={{ maxWidth: 900, margin: "0 auto", padding: "48px 20px" }}>
      {!w.connected ? (
        <div style={{ textAlign: "center", padding: "80px 0" }}>
          <IconShield size={48} color={C.textDim} />
          <div style={{ fontSize: 20, fontWeight: 700, marginTop: 16, marginBottom: 8 }}>Connect Your Wallet</div>
          <div style={{ fontSize: 14, color: C.textSec, marginBottom: 24, fontWeight: 300 }}>View your positions, accrued yield, and history.</div>
          <button onClick={() => w.connect()} style={{ padding: "12px 32px", borderRadius: 10, border: "none", cursor: "pointer", fontSize: 14, fontWeight: 600, color: "#000", background: C.gradBtn, fontFamily: font }}>Connect Wallet</button>
        </div>
      ) : (
        <div>
          <h2 style={{ fontSize: 26, fontWeight: 700, letterSpacing: "-0.03em", marginBottom: 24 }}>Dashboard</h2>
          <div style={{ display: "grid", gridTemplateColumns: "repeat(auto-fit, minmax(180px, 1fr))", gap: 12, marginBottom: 24 }}>
            {([["xSTRK Balance", w.balances.xSTRK + " xSTRK", ""], ["PT Balance", w.balances.PT + " PT", C.teal], ["YT Balance", w.balances.YT + " YT", C.amber], ["Positions", String([w.balances.PT, w.balances.YT, w.balances.SY].filter(b => b !== "0" && parseFloat(b) > 0).length), ""]] as [string, string, string][]).map(([l, v, c], i) => (
              <div key={i} style={{ background: C.bgCard, borderRadius: 12, border: `1px solid ${C.border}`, padding: "16px 20px" }}>
                <div style={{ fontSize: 9, color: C.textDim, textTransform: "uppercase", letterSpacing: "0.1em", marginBottom: 6, fontWeight: 500 }}>{l}</div>
                <div style={{ fontSize: 15, fontWeight: 600, fontFamily: mono, color: c || C.text }}>{v}</div>
              </div>
            ))}
          </div>
          <div style={{ background: C.bgCard, borderRadius: 14, border: `1px solid ${C.border}`, padding: 22 }}>
            <div style={{ fontSize: 14, fontWeight: 600, marginBottom: 16 }}>Active Positions</div>
            {[{ token: "PT-xSTRK", amount: w.balances.PT, apy: "5.8%", color: C.teal }, { token: "YT-xSTRK", amount: w.balances.YT, apy: "14.3%", color: C.amber }, { token: "SY-xSTRK", amount: w.balances.SY, apy: "-", color: C.blue }]
              .filter(p => p.amount !== "0" && parseFloat(p.amount) > 0).map((p, i) => (
                <div key={i} style={{ display: "flex", justifyContent: "space-between", padding: "12px 0", borderBottom: `1px solid ${C.border}` }}>
                  <div style={{ display: "flex", alignItems: "center", gap: 10 }}>
                    <div style={{ width: 28, height: 28, borderRadius: 8, background: `${p.color}12`, display: "flex", alignItems: "center", justifyContent: "center", fontSize: 10, fontWeight: 700, color: p.color }}>{p.token.slice(0, 2)}</div>
                    <div><div style={{ fontSize: 14, fontWeight: 500 }}>{p.token}</div><div style={{ fontSize: 11, color: C.textDim, fontFamily: mono }}>{p.amount}</div></div>
                  </div>
                  <div style={{ fontSize: 13, fontFamily: mono, color: p.color, fontWeight: 600, alignSelf: "center" }}>{p.apy}</div>
                </div>
              ))}
            {parseFloat(w.balances.PT || "0") === 0 && parseFloat(w.balances.YT || "0") === 0 && parseFloat(w.balances.SY || "0") === 0 && <div style={{ fontSize: 13, color: C.textDim, textAlign: "center", padding: 24 }}>No positions yet. Start trading to see your positions here.</div>}
          </div>
          {parseFloat(w.balances.YT || "0") > 0 && (
            <div style={{ marginTop: 16, background: `${C.teal}08`, border: `1px solid ${C.teal}22`, borderRadius: 14, padding: "18px 22px", display: "flex", alignItems: "center", justifyContent: "space-between", flexWrap: "wrap", gap: 12 }}>
              <div><div style={{ fontSize: 12, color: C.textSec, marginBottom: 4 }}>Claimable from YT-xSTRK</div><div style={{ fontSize: 20, fontWeight: 700, fontFamily: mono, color: C.teal }}>{w.balances.YT} YT-xSTRK</div></div>
              <button onClick={() => w.claimYield()} style={{ padding: "10px 24px", borderRadius: 10, border: "none", cursor: "pointer", fontSize: 13, fontWeight: 600, color: "#000", background: C.teal, fontFamily: font }}>Claim Yield</button>
            </div>
          )}
        </div>
      )}
    </div>
  );
}

// ═══════ MAIN APP ═══════
export default function App() {
  const [page, setPage] = useState("landing");
  const [market, setMarket] = useState(0);
  const [strategy, setStrategy] = useState<string | null>(null);
  const w = useWallet();

  return (
    <div style={{ minHeight: "100vh", background: C.bg, color: C.text, fontFamily: font }}>
      <link href="https://fonts.googleapis.com/css2?family=Outfit:wght@300;400;500;600;700;800&family=JetBrains+Mono:wght@400;500;600&display=swap" rel="stylesheet" />

      {page === "landing" && <LandingPage onEnter={() => setPage("markets")} />}

      {page !== "landing" && (
        <header style={{ display: "flex", alignItems: "center", justifyContent: "space-between", padding: "0 clamp(12px,3vw,28px)", height: 56, borderBottom: `1px solid ${C.border}`, position: "sticky", top: 0, zIndex: 40, background: `${C.bg}ee`, backdropFilter: "blur(12px)" }}>
          <div style={{ display: "flex", alignItems: "center", gap: 20 }}>
            <div style={{ display: "flex", alignItems: "center", gap: 8, cursor: "pointer" }} onClick={() => setPage("landing")}><FissionLogo size={20} /><span style={{ fontSize: 15, fontWeight: 700, letterSpacing: "-0.03em" }}>fission</span></div>
            <nav style={{ display: "flex", gap: 2 }}>
              {(["markets", "dashboard"] as const).map(p => (
                <button key={p} onClick={() => setPage(p)} style={{ padding: "6px 14px", border: "none", borderRadius: 8, cursor: "pointer", fontSize: 12, fontWeight: 500, fontFamily: font,
                  background: page === p || (p === "markets" && (page === "strategy" || page === "trade")) ? C.bgHover : "transparent",
                  color: page === p || (p === "markets" && (page === "strategy" || page === "trade")) ? C.text : C.textSec }}>{p.charAt(0).toUpperCase() + p.slice(1)}</button>
              ))}
            </nav>
          </div>
          <div style={{ display: "flex", alignItems: "center", gap: 10 }}>
            <div style={{ display: "flex", alignItems: "center", gap: 5 }}><div style={{ width: 5, height: 5, borderRadius: "50%", background: C.teal }} /><span style={{ fontSize: 11, color: C.textSec }}>Mainnet</span></div>
            <button onClick={() => w.connected ? w.disconnect() : w.connect()} style={{ padding: "7px 18px", border: w.connected ? `1px solid ${C.borderHover}` : "none", borderRadius: 8, cursor: "pointer", fontSize: 12, fontWeight: 600, fontFamily: font, color: w.connected ? C.text : "#000", background: w.connected ? C.bgCard : C.gradBtn }}>
              {w.loading ? "Connecting..." : w.connected ? w.shortAddress : "Connect Wallet"}
            </button>
          </div>
        </header>
      )}

      {page === "markets" && <MarketsPage onSelect={id => { setMarket(id); setPage("strategy"); }} />}
      {page === "strategy" && <StrategyPage market={market} onSelect={s => { setStrategy(s); setPage("trade"); }} onBack={() => setPage("markets")} />}
      {page === "trade" && strategy && <TradePage market={market} strategy={strategy} onBack={() => setPage("strategy")} w={w} />}
      {page === "dashboard" && <DashboardPage w={w} />}
    </div>
  );
}
